/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedInvoiceNumberRouteImport } from './routes/_authenticated/invoice.$number'
import { Route as AuthenticatedAdminAgencyIdRouteImport } from './routes/_authenticated/admin.agency.$id'
import { Route as AuthenticatedAdminCustomerIdRouteImport } from './routes/_authenticated/admin.customer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInvoiceNumberRoute =
  AuthenticatedInvoiceNumberRouteImport.update({
    id: '/invoice/$number',
    path: '/invoice/$number',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAgencyIdRoute =
  AuthenticatedAdminAgencyIdRouteImport.update({
    id: '/agency/$id',
    path: '/agency/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomerIdRoute =
  AuthenticatedAdminCustomerIdRouteImport.update({
    id: '/customer/$id',
    path: '/customer/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/offers/': typeof OffersIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/invoice/$number': typeof AuthenticatedInvoiceNumberRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/agency/$id': typeof AuthenticatedAdminAgencyIdRoute
  '/admin/customer/$id': typeof AuthenticatedAdminCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/track': typeof TrackRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/offers': typeof OffersIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/invoice/$number': typeof AuthenticatedInvoiceNumberRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/agency/$id': typeof AuthenticatedAdminAgencyIdRoute
  '/admin/customer/$id': typeof AuthenticatedAdminCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/track': typeof TrackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/offers/': typeof OffersIndexRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/invoice/$number': typeof AuthenticatedInvoiceNumberRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/agency/$id': typeof AuthenticatedAdminAgencyIdRoute
  '/_authenticated/admin/customer/$id': typeof AuthenticatedAdminCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/catalog'
    | '/track'
    | '/admin'
    | '/checkout/$slug'
    | '/offers/$slug'
    | '/offers/'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/partners'
    | '/invoice/$number'
    | '/admin/'
    | '/admin/agency/$id'
    | '/admin/customer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/catalog'
    | '/track'
    | '/checkout/$slug'
    | '/offers/$slug'
    | '/offers'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/partners'
    | '/invoice/$number'
    | '/admin'
    | '/admin/agency/$id'
    | '/admin/customer/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/auth'
    | '/catalog'
    | '/track'
    | '/_authenticated/admin'
    | '/checkout/$slug'
    | '/offers/$slug'
    | '/offers/'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/partners'
    | '/_authenticated/invoice/$number'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/agency/$id'
    | '/_authenticated/admin/customer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  TrackRoute: typeof TrackRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  OffersSlugRoute: typeof OffersSlugRoute
  OffersIndexRoute: typeof OffersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/invoice/$number': {
      id: '/_authenticated/invoice/$number'
      path: '/invoice/$number'
      fullPath: '/invoice/$number'
      preLoaderRoute: typeof AuthenticatedInvoiceNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agency/$id': {
      id: '/_authenticated/admin/agency/$id'
      path: '/agency/$id'
      fullPath: '/admin/agency/$id'
      preLoaderRoute: typeof AuthenticatedAdminAgencyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customer/$id': {
      id: '/_authenticated/admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/admin/customer/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAgencyIdRoute: typeof AuthenticatedAdminAgencyIdRoute
  AuthenticatedAdminCustomerIdRoute: typeof AuthenticatedAdminCustomerIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAgencyIdRoute: AuthenticatedAdminAgencyIdRoute,
  AuthenticatedAdminCustomerIdRoute: AuthenticatedAdminCustomerIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInvoiceNumberRoute: typeof AuthenticatedInvoiceNumberRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInvoiceNumberRoute: AuthenticatedInvoiceNumberRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  TrackRoute: TrackRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  OffersSlugRoute: OffersSlugRoute,
  OffersIndexRoute: OffersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
