/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAgenciesRouteImport } from './routes/_authenticated/admin.agencies'
import { Route as AuthenticatedAdminBalancesRouteImport } from './routes/_authenticated/admin.balances'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminEmailNotificationsRouteImport } from './routes/_authenticated/admin.email-notifications'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminFlightsRouteImport } from './routes/_authenticated/admin.flights'
import { Route as AuthenticatedAdminLinksRouteImport } from './routes/_authenticated/admin.links'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin.offers'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAgencyIndexRouteImport } from './routes/_authenticated/agency.index'
import { Route as AuthenticatedAgencyBalanceRouteImport } from './routes/_authenticated/agency.balance'
import { Route as AuthenticatedAgencyCustomersRouteImport } from './routes/_authenticated/agency.customers'
import { Route as AuthenticatedAgencyOffersRouteImport } from './routes/_authenticated/agency.offers'
import { Route as AuthenticatedAgencyOrdersRouteImport } from './routes/_authenticated/agency.orders'
import { Route as AuthenticatedAgencyStatementRouteImport } from './routes/_authenticated/agency.statement'
import { Route as AuthenticatedInvoiceNumberRouteImport } from './routes/_authenticated/invoice.$number'
import { Route as ApiPublicEmailDispatchRouteImport } from './routes/api/public/email-dispatch'
import { Route as AuthenticatedAdminAgencyIdRouteImport } from './routes/_authenticated/admin.agency.$id'
import { Route as AuthenticatedAdminCustomerIdRouteImport } from './routes/_authenticated/admin.customer.$id'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAgenciesRoute =
  AuthenticatedAdminAgenciesRouteImport.update({
    id: '/agencies',
    path: '/agencies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBalancesRoute =
  AuthenticatedAdminBalancesRouteImport.update({
    id: '/balances',
    path: '/balances',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailNotificationsRoute =
  AuthenticatedAdminEmailNotificationsRouteImport.update({
    id: '/email-notifications',
    path: '/email-notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlightsRoute =
  AuthenticatedAdminFlightsRouteImport.update({
    id: '/flights',
    path: '/flights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLinksRoute = AuthenticatedAdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAgencyIndexRoute =
  AuthenticatedAgencyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)
const AuthenticatedAgencyBalanceRoute =
  AuthenticatedAgencyBalanceRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)
const AuthenticatedAgencyCustomersRoute =
  AuthenticatedAgencyCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)
const AuthenticatedAgencyOffersRoute =
  AuthenticatedAgencyOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)
const AuthenticatedAgencyOrdersRoute =
  AuthenticatedAgencyOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)
const AuthenticatedAgencyStatementRoute =
  AuthenticatedAgencyStatementRouteImport.update({
    id: '/statement',
    path: '/statement',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)
const AuthenticatedInvoiceNumberRoute =
  AuthenticatedInvoiceNumberRouteImport.update({
    id: '/invoice/$number',
    path: '/invoice/$number',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicEmailDispatchRoute = ApiPublicEmailDispatchRouteImport.update({
  id: '/api/public/email-dispatch',
  path: '/api/public/email-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAgencyIdRoute =
  AuthenticatedAdminAgencyIdRouteImport.update({
    id: '/agency/$id',
    path: '/agency/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomerIdRoute =
  AuthenticatedAdminCustomerIdRouteImport.update({
    id: '/customer/$id',
    path: '/customer/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agency': typeof AuthenticatedAgencyRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/offers/': typeof OffersIndexRoute
  '/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/admin/balances': typeof AuthenticatedAdminBalancesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/email-notifications': typeof AuthenticatedAdminEmailNotificationsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/admin/links': typeof AuthenticatedAdminLinksRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agency/balance': typeof AuthenticatedAgencyBalanceRoute
  '/agency/customers': typeof AuthenticatedAgencyCustomersRoute
  '/agency/offers': typeof AuthenticatedAgencyOffersRoute
  '/agency/orders': typeof AuthenticatedAgencyOrdersRoute
  '/agency/statement': typeof AuthenticatedAgencyStatementRoute
  '/invoice/$number': typeof AuthenticatedInvoiceNumberRoute
  '/api/public/email-dispatch': typeof ApiPublicEmailDispatchRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agency/': typeof AuthenticatedAgencyIndexRoute
  '/admin/agency/$id': typeof AuthenticatedAdminAgencyIdRoute
  '/admin/customer/$id': typeof AuthenticatedAdminCustomerIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/track': typeof TrackRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/offers': typeof OffersIndexRoute
  '/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/admin/balances': typeof AuthenticatedAdminBalancesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/email-notifications': typeof AuthenticatedAdminEmailNotificationsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/admin/links': typeof AuthenticatedAdminLinksRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agency/balance': typeof AuthenticatedAgencyBalanceRoute
  '/agency/customers': typeof AuthenticatedAgencyCustomersRoute
  '/agency/offers': typeof AuthenticatedAgencyOffersRoute
  '/agency/orders': typeof AuthenticatedAgencyOrdersRoute
  '/agency/statement': typeof AuthenticatedAgencyStatementRoute
  '/invoice/$number': typeof AuthenticatedInvoiceNumberRoute
  '/api/public/email-dispatch': typeof ApiPublicEmailDispatchRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agency': typeof AuthenticatedAgencyIndexRoute
  '/admin/agency/$id': typeof AuthenticatedAdminAgencyIdRoute
  '/admin/customer/$id': typeof AuthenticatedAdminCustomerIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/track': typeof TrackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agency': typeof AuthenticatedAgencyRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/offers/': typeof OffersIndexRoute
  '/_authenticated/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/_authenticated/admin/balances': typeof AuthenticatedAdminBalancesRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/email-notifications': typeof AuthenticatedAdminEmailNotificationsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/_authenticated/admin/links': typeof AuthenticatedAdminLinksRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agency/balance': typeof AuthenticatedAgencyBalanceRoute
  '/_authenticated/agency/customers': typeof AuthenticatedAgencyCustomersRoute
  '/_authenticated/agency/offers': typeof AuthenticatedAgencyOffersRoute
  '/_authenticated/agency/orders': typeof AuthenticatedAgencyOrdersRoute
  '/_authenticated/agency/statement': typeof AuthenticatedAgencyStatementRoute
  '/_authenticated/invoice/$number': typeof AuthenticatedInvoiceNumberRoute
  '/api/public/email-dispatch': typeof ApiPublicEmailDispatchRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agency/': typeof AuthenticatedAgencyIndexRoute
  '/_authenticated/admin/agency/$id': typeof AuthenticatedAdminAgencyIdRoute
  '/_authenticated/admin/customer/$id': typeof AuthenticatedAdminCustomerIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/catalog'
    | '/track'
    | '/admin'
    | '/agency'
    | '/checkout/$slug'
    | '/offers/$slug'
    | '/offers/'
    | '/admin/agencies'
    | '/admin/balances'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/email-notifications'
    | '/admin/finance'
    | '/admin/flights'
    | '/admin/links'
    | '/admin/offers'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/agency/balance'
    | '/agency/customers'
    | '/agency/offers'
    | '/agency/orders'
    | '/agency/statement'
    | '/invoice/$number'
    | '/api/public/email-dispatch'
    | '/admin/'
    | '/agency/'
    | '/admin/agency/$id'
    | '/admin/customer/$id'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/catalog'
    | '/track'
    | '/checkout/$slug'
    | '/offers/$slug'
    | '/offers'
    | '/admin/agencies'
    | '/admin/balances'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/email-notifications'
    | '/admin/finance'
    | '/admin/flights'
    | '/admin/links'
    | '/admin/offers'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/agency/balance'
    | '/agency/customers'
    | '/agency/offers'
    | '/agency/orders'
    | '/agency/statement'
    | '/invoice/$number'
    | '/api/public/email-dispatch'
    | '/admin'
    | '/agency'
    | '/admin/agency/$id'
    | '/admin/customer/$id'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/auth'
    | '/catalog'
    | '/track'
    | '/_authenticated/admin'
    | '/_authenticated/agency'
    | '/checkout/$slug'
    | '/offers/$slug'
    | '/offers/'
    | '/_authenticated/admin/agencies'
    | '/_authenticated/admin/balances'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/email-notifications'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/flights'
    | '/_authenticated/admin/links'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/agency/balance'
    | '/_authenticated/agency/customers'
    | '/_authenticated/agency/offers'
    | '/_authenticated/agency/orders'
    | '/_authenticated/agency/statement'
    | '/_authenticated/invoice/$number'
    | '/api/public/email-dispatch'
    | '/_authenticated/admin/'
    | '/_authenticated/agency/'
    | '/_authenticated/admin/agency/$id'
    | '/_authenticated/admin/customer/$id'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  TrackRoute: typeof TrackRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  OffersSlugRoute: typeof OffersSlugRoute
  OffersIndexRoute: typeof OffersIndexRoute
  ApiPublicEmailDispatchRoute: typeof ApiPublicEmailDispatchRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agencies': {
      id: '/_authenticated/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AuthenticatedAdminAgenciesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/balances': {
      id: '/_authenticated/admin/balances'
      path: '/balances'
      fullPath: '/admin/balances'
      preLoaderRoute: typeof AuthenticatedAdminBalancesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-notifications': {
      id: '/_authenticated/admin/email-notifications'
      path: '/email-notifications'
      fullPath: '/admin/email-notifications'
      preLoaderRoute: typeof AuthenticatedAdminEmailNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flights': {
      id: '/_authenticated/admin/flights'
      path: '/flights'
      fullPath: '/admin/flights'
      preLoaderRoute: typeof AuthenticatedAdminFlightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/links': {
      id: '/_authenticated/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AuthenticatedAdminLinksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/agency/': {
      id: '/_authenticated/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AuthenticatedAgencyIndexRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/agency/balance': {
      id: '/_authenticated/agency/balance'
      path: '/balance'
      fullPath: '/agency/balance'
      preLoaderRoute: typeof AuthenticatedAgencyBalanceRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/agency/customers': {
      id: '/_authenticated/agency/customers'
      path: '/customers'
      fullPath: '/agency/customers'
      preLoaderRoute: typeof AuthenticatedAgencyCustomersRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/agency/offers': {
      id: '/_authenticated/agency/offers'
      path: '/offers'
      fullPath: '/agency/offers'
      preLoaderRoute: typeof AuthenticatedAgencyOffersRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/agency/orders': {
      id: '/_authenticated/agency/orders'
      path: '/orders'
      fullPath: '/agency/orders'
      preLoaderRoute: typeof AuthenticatedAgencyOrdersRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/agency/statement': {
      id: '/_authenticated/agency/statement'
      path: '/statement'
      fullPath: '/agency/statement'
      preLoaderRoute: typeof AuthenticatedAgencyStatementRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/invoice/$number': {
      id: '/_authenticated/invoice/$number'
      path: '/invoice/$number'
      fullPath: '/invoice/$number'
      preLoaderRoute: typeof AuthenticatedInvoiceNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/email-dispatch': {
      id: '/api/public/email-dispatch'
      path: '/api/public/email-dispatch'
      fullPath: '/api/public/email-dispatch'
      preLoaderRoute: typeof ApiPublicEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/agency/$id': {
      id: '/_authenticated/admin/agency/$id'
      path: '/agency/$id'
      fullPath: '/admin/agency/$id'
      preLoaderRoute: typeof AuthenticatedAdminAgencyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customer/$id': {
      id: '/_authenticated/admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/admin/customer/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgenciesRoute: typeof AuthenticatedAdminAgenciesRoute
  AuthenticatedAdminBalancesRoute: typeof AuthenticatedAdminBalancesRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEmailNotificationsRoute: typeof AuthenticatedAdminEmailNotificationsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminFlightsRoute: typeof AuthenticatedAdminFlightsRoute
  AuthenticatedAdminLinksRoute: typeof AuthenticatedAdminLinksRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAgencyIdRoute: typeof AuthenticatedAdminAgencyIdRoute
  AuthenticatedAdminCustomerIdRoute: typeof AuthenticatedAdminCustomerIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgenciesRoute: AuthenticatedAdminAgenciesRoute,
  AuthenticatedAdminBalancesRoute: AuthenticatedAdminBalancesRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEmailNotificationsRoute:
    AuthenticatedAdminEmailNotificationsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminFlightsRoute: AuthenticatedAdminFlightsRoute,
  AuthenticatedAdminLinksRoute: AuthenticatedAdminLinksRoute,
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAgencyIdRoute: AuthenticatedAdminAgencyIdRoute,
  AuthenticatedAdminCustomerIdRoute: AuthenticatedAdminCustomerIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAgencyRouteChildren {
  AuthenticatedAgencyBalanceRoute: typeof AuthenticatedAgencyBalanceRoute
  AuthenticatedAgencyCustomersRoute: typeof AuthenticatedAgencyCustomersRoute
  AuthenticatedAgencyOffersRoute: typeof AuthenticatedAgencyOffersRoute
  AuthenticatedAgencyOrdersRoute: typeof AuthenticatedAgencyOrdersRoute
  AuthenticatedAgencyStatementRoute: typeof AuthenticatedAgencyStatementRoute
  AuthenticatedAgencyIndexRoute: typeof AuthenticatedAgencyIndexRoute
}

const AuthenticatedAgencyRouteChildren: AuthenticatedAgencyRouteChildren = {
  AuthenticatedAgencyBalanceRoute: AuthenticatedAgencyBalanceRoute,
  AuthenticatedAgencyCustomersRoute: AuthenticatedAgencyCustomersRoute,
  AuthenticatedAgencyOffersRoute: AuthenticatedAgencyOffersRoute,
  AuthenticatedAgencyOrdersRoute: AuthenticatedAgencyOrdersRoute,
  AuthenticatedAgencyStatementRoute: AuthenticatedAgencyStatementRoute,
  AuthenticatedAgencyIndexRoute: AuthenticatedAgencyIndexRoute,
}

const AuthenticatedAgencyRouteWithChildren =
  AuthenticatedAgencyRoute._addFileChildren(AuthenticatedAgencyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRouteWithChildren
  AuthenticatedInvoiceNumberRoute: typeof AuthenticatedInvoiceNumberRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgencyRoute: AuthenticatedAgencyRouteWithChildren,
  AuthenticatedInvoiceNumberRoute: AuthenticatedInvoiceNumberRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  TrackRoute: TrackRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  OffersSlugRoute: OffersSlugRoute,
  OffersIndexRoute: OffersIndexRoute,
  ApiPublicEmailDispatchRoute: ApiPublicEmailDispatchRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
