revoke execute on function public.handle_new_user() from public;
revoke execute on function public.set_updated_at() from public;
revoke execute on function public.next_tracking_id() from public;
revoke execute on function public.assign_tracking_id() from public;
revoke execute on function public.has_role(uuid, public.app_role) from public;
revoke execute on function public.is_staff(uuid) from public;
revoke execute on function public.is_admin(uuid) from public;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.is_staff(uuid) to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;